CREATE TABLE `tm_alumno_edu` (
  `idAlumno` int NOT NULL,
  `nomUsuario` varchar(60) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT 'Nombre del usuario que va a acceder',
  `emailUsuario` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL,
  `senaUsuario` varchar(45) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT 'Contraseña del usuario que va a acceder',
  `fecAltaUsuario` datetime DEFAULT NULL,
  `fecBajaUsuario` datetime DEFAULT NULL,
  `fecModiUsuario` datetime DEFAULT NULL,
  `avatarUsuario` varchar(225) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT 'avatarUsuario',
  `estUsu` int DEFAULT NULL,
  `nomAlumno` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT 'Nombre del alumno',
  `apeAlumno` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT 'Apellido del alumno',
  `fecNacAlumno` date DEFAULT NULL COMMENT '1- Fecha de nacimiento del alumno',
  `nacioAlumno` varchar(75) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '1- Nacionalidad del alumno (Española, Inglesa, etc..)',
  `ProfeEstuAlumno` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '1- Profesión, Estudios máximos del alumno',
  `EmpresaAlumno` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '1- En el caso de trabajar, nombre de la empresa',
  `UniAlumno` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '1- Si proviene de universidad, el nombre de la misma',
  `teleAlumno` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '1-Teléfono del alumno',
  `domValAlumno` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '1- Domicilio en Valencia',
  `domOrigenAlumno` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '1- Domicilio en el pais de origen',
  `lenMatAlumno` varchar(120) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '2 - A - Lenguajes maternos',
  `lenCon1Alumno` varchar(70) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '2- A - Lenguajes que conoce - 1 (De un total de 4)',
  `lenCon2Alumno` varchar(70) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '2- A - Lenguajes que conoce - 2 (De un total de 4)',
  `lenCon3Alumno` varchar(70) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '2- A - Lenguajes que conoce - 3 (De un total de 4)',
  `lenCon4Alumno` varchar(70) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '2- A - Lenguajes que conoce - 4 (De un total de 4)',
  `estEspAlumno` int DEFAULT NULL COMMENT '2 - A - ¿Has estudiado antes español? (Si = 1, 0 = No)',
  `nivEspAlumno` varchar(120) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '2 - A - Nivel alcanzado de Español',
  `tiemEspAlumno` varchar(70) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '2 - A - Cuanto tiempo has estudiado español',
  `lugEspAlumno` varchar(120) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '2 - A - donde has estudiado español?',
  `porEspAlumno` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci COMMENT '2 - B - Por que quieres aprender español.',
  `mejEspAlumno` int DEFAULT NULL COMMENT '2 - B - ¿que necesitas mejorar en Español?\n1 = Comprensión auditiva\n2 = Comprensión lectora\n3 = Expresión oral\n4 = Expresión escrita\n5 = Pronunciación\n6 = Vocabulario\n7 = Gramática\n8 = Cultura',
  `aprEspAlumno` int DEFAULT NULL COMMENT '2 - C - ¿Como aprendo?\n1 = Leer\n2 = Escuchar\n3 = Escribir\n4 = Hablar\n5 = Traducir a mi idioma\n6 = Estar con nativos',
  `act1Alumno` int DEFAULT NULL COMMENT '2 - C - ¿que actividades te gusta hacer en clase? \nActividades comunicativas\n1 = Si, 0 = No (1 / 7)',
  `act2Alumno` int DEFAULT NULL COMMENT '2 - C - ¿que actividades te gusta hacer en clase? \nAprender Vocabulario\n1 = Si, 0 = No (2 / 7)',
  `act3Alumno` int DEFAULT NULL COMMENT '2 - C - ¿que actividades te gusta hacer en clase? \nAprender con juegos\n1 = Si, 0 = No (3 / 7)',
  `act4Alumno` int DEFAULT NULL COMMENT '2 - C - ¿que actividades te gusta hacer en clase? \nPracticar gramática\n1 = Si, 0 = No (4 / 7)',
  `act5Alumno` int DEFAULT NULL COMMENT '2 - C - ¿que actividades te gusta hacer en clase? \nActividades Audiovisuales\n1 = Si, 0 = No (5 / 7)',
  `act6Alumno` int DEFAULT NULL COMMENT '2 - C - ¿que actividades te gusta hacer en clase? \nActividades interactivas\n1 = Si, 0 = No (6 / 7)',
  `act7Alumno` int DEFAULT NULL COMMENT '2 - C - ¿que actividades te gusta hacer en clase? \nHacer deberes\n1 = Si, 0 = No (7 / 7)',
  `gustaTraAlumno` int DEFAULT NULL COMMENT '2 - C - ¿como te gusta trabajar?\n1 = solo\n2 = En parejas\n3 = Grupos',
  `gus1EspAlumno` int DEFAULT NULL COMMENT '2 - D - Durante mi curso de Español me gustaría.\nGanar fluidez y seguridad al comunicarme\n1 = Si, 0 = No',
  `gus2EspAlumno` int DEFAULT NULL COMMENT '2 - D - Durante mi curso de Español me gustaría.\nrevisar contenidos dificiles para mi\n1 = Si, 0 = No',
  `gus3EspAlumno` int DEFAULT NULL COMMENT '2 - D - Durante mi curso de Español me gustaría.\nMejorar mis calificaciones de español\n1 = Si, 0 = No',
  `gus4EspAlumno` int DEFAULT NULL COMMENT '2 - D - Durante mi curso de Español me gustaría.\nAprender nuevos contenidos\n1 = Si, 0 = No',
  `gus5EspAlumno` int DEFAULT NULL COMMENT '2 - D - Durante mi curso de Español me gustaría.\nOtros\n1 = Si, 0 = No',
  `gusTextEspAlumno` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT 'Se activará cuando se gus5EspAlumno = 1 (otros)',
  `conAlumno` int DEFAULT NULL COMMENT '3 - como nos ha conocido\n1 = Internet\n2 = Recomendacion\n3 = Agencia\n4 = Anuncio',
  `conRecoAlumno` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '3 - en caso de que conAlumno= 2 habilitamos para este añadir descripción',
  `conAgenAlumno` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '3 - En caso de que conAlumno = 3, habilitar este campo para meter nombre de la agencia',
  `actSocialesAlumno` int DEFAULT NULL COMMENT '4 - Actividades extraacadémicas\nActividades Sociales\n1 = Si 0=No',
  `actCultAlumno` int DEFAULT NULL COMMENT '4 - Actividades extraacadémicas\nActividades culturales\n1 = Si 0=No',
  `actGastroAlumno` int DEFAULT NULL COMMENT '4 - Actividades extraacadémicas\nActividades Gastronómicas\n1 = Si 0=No',
  `actDepoAlumno` int DEFAULT NULL COMMENT '4 - Actividades extraacadémicas\nActividades Deportivas\n1 = Si 0=No',
  `partActAlumno` int DEFAULT NULL COMMENT '4 - ¿Te gustaría participar?\n1 = Si 0=No',
  `numActAlumno` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '4 - Actividades extraacadémicas\ntu número de móvil para participar en grupo de WhatsApp',
  `UltimaSesion` date DEFAULT NULL,
  `tokenUsu` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci,
  `identificadorPersonal` varchar(120) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT 'NIF, DNI, Numero identificativo',
  `perfilBloqueado` tinyint(1) DEFAULT '0',
  `idInscripcion_tmAlumno` int DEFAULT NULL COMMENT 'Viene de la tabla de inscripcion al crear la isncripcion',
  `idUsuario_tmalumno` int DEFAULT NULL COMMENT 'Viene de la tabla tm_usuario al crear el usuario ',
  `depaActivo` varchar(50) COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT '0/1 si tiene un departamento PAGADO Activo. Cuando se caduque sera 0',
  `depasNameActivos` varchar(255) COLLATE utf8mb3_spanish2_ci DEFAULT NULL COMMENT 'Nos dira concretamente que departametnos estan activos',
  `agoraAlumno` int DEFAULT NULL COMMENT 'Es agorofobico. Espacios cerrados',
  `minusvaliaAlumno` int DEFAULT NULL COMMENT 'minusvalia',
  `obsMinusvaliaAlumno` longtext COLLATE utf8mb3_spanish2_ci COMMENT 'motivos, que le ocurre, medicamentos, etc'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_spanish2_ci COMMENT='Tabla de usuarios';

