CREATE TABLE `tm_llegadas_edu` (
  `id_llegada` int NOT NULL,
  `diainscripcion_llegadas` date DEFAULT NULL,
  `idprescriptor_llegadas` int DEFAULT NULL,
  `iddepartamento_llegadas` int DEFAULT NULL,
  `agente_llegadas` int DEFAULT NULL,
  `grupo_llegadas` varchar(100) DEFAULT NULL,
  `grupoAmigos` varchar(255) DEFAULT NULL,
  `fechallegada_llegadas` datetime DEFAULT NULL,
  `horallegada_llegadas` time DEFAULT NULL,
  `lugarllegada_llegadas` text,
  `quienrecogealumno_llegadas` varchar(255) DEFAULT NULL,
  `fechacancelacion_llegadas` date DEFAULT NULL,
  `motivocancelacion_llegadas` text,
  `codigotariotallegadaTransfer_llegadas` varchar(50) DEFAULT NULL,
  `textotariotallegadaTransfer_llegadas` text,
  `importetariotallegadaTransfer_llegadas` varchar(100) DEFAULT NULL,
  `ivatariotallegadaTransfer_llegadas` varchar(100) DEFAULT NULL,
  `diallegadaTransferTransfer_llegadas` date DEFAULT NULL,
  `horallegadaTransferTransfer_llegadas` time DEFAULT NULL,
  `lugarllegadallegadaTransfer_llegadas` text,
  `lugarentregallegadaTransfer_llegadas` text,
  `quienrecogealumnollegadaTransfer_llegadas` varchar(255) DEFAULT NULL,
  `codigotariotalregresoTransfer_llegadas` varchar(50) DEFAULT NULL,
  `textotariotalregresoTransfer_llegadas` text,
  `importetariotalregresoTransfer_llegadas` varchar(100) DEFAULT NULL,
  `ivatariotalregresoTransfer_llegadas` varchar(100) DEFAULT NULL,
  `diaregresoTransfer_llegadas` date DEFAULT NULL,
  `horaregresoTransfer_llegadas` time DEFAULT NULL,
  `lugarrecogidaregresaTransfer_llegadas` text,
  `lugarentregaregresaTransfer_llegadas` text,
  `quienrecogealumnoregresaTransfer_llegadas` varchar(255) DEFAULT NULL,
  `campoobservacionesgeneralTransfer_llegadas` text,
  `niveldice_llegadas` text,
  `nivelobservaciones_llegadas` text,
  `nivelasignado_llegadas` varchar(100) DEFAULT NULL,
  `semanaasignada_llegadas` varchar(100) DEFAULT NULL,
  `tieneVisado` int DEFAULT NULL,
  `fechCartaAdmision` date DEFAULT NULL,
  `denegacionFecha` date DEFAULT NULL,
  `denegacionMotivo` longtext,
  `estProforma` int DEFAULT '0',
  `numProforma` varchar(255) DEFAULT NULL,
  `estLlegada` int NOT NULL DEFAULT '1',
  `suplidoImporte` varchar(100) DEFAULT NULL,
  `suplidoDescr` varchar(255) DEFAULT NULL,
  `estMatricula` int DEFAULT '4' COMMENT 'Estaedo de la matricula (Valor del 1 al 4)',
  `estAlojamiento` int DEFAULT '4' COMMENT 'Si tiene alojamiento o no (Valor del 1 al 4)',
  `cursoFinalizado` int DEFAULT NULL COMMENT 'Cuando un alumno finaliza 100% un curso, para certificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
