CREATE TABLE `tm_prescriptores` (
  `idPrescripcion` int NOT NULL,
  `nomPrescripcion` varchar(255) DEFAULT NULL,
  `apePrescripcion` varchar(255) DEFAULT NULL,
  `sexoPrescripcion` varchar(255) DEFAULT NULL,
  `fecNacPrescripcion` date DEFAULT NULL,
  `anoPrevistoPrescripcion` varchar(255) DEFAULT NULL,
  `emailCasaPrescripcion` varchar(255) DEFAULT NULL,
  `emailAltPrescripcion` varchar(255) DEFAULT NULL,
  `fechContactoPrescripcion` date DEFAULT NULL,
  `dirCasaPrescripcion` varchar(255) DEFAULT NULL,
  `dirAltPrescripcion` varchar(255) DEFAULT NULL,
  `cursoPrescripcion` varchar(255) DEFAULT NULL,
  `cpCasaPrescripcion` varchar(255) DEFAULT NULL,
  `cpAltPrescripcion` varchar(255) DEFAULT NULL,
  `cono1Prescripcion` varchar(255) DEFAULT NULL,
  `ciudadCasaPrescripcion` varchar(255) DEFAULT NULL,
  `ciudadAltPrescripcion` varchar(255) DEFAULT NULL,
  `cono2Prescripcion` varchar(255) DEFAULT NULL,
  `paisCasaPrescripcion` varchar(255) DEFAULT NULL,
  `paisAltPrescripcion` varchar(255) DEFAULT NULL,
  `cono3Prescripcion` varchar(255) DEFAULT NULL,
  `tefCasaPrescripcion` varchar(255) DEFAULT NULL,
  `tefAltPrescripcion` varchar(255) DEFAULT NULL,
  `probablementePrescripcion` varchar(255) DEFAULT NULL,
  `movilCasaPrescripcion` varchar(255) DEFAULT NULL,
  `movilAltPrescripcion` varchar(255) DEFAULT NULL,
  `grupoPrescripcion` varchar(255) DEFAULT NULL,
  `erasmusPrescripcion` varchar(255) DEFAULT NULL,
  `uniOrigenPrescripcion` varchar(255) DEFAULT NULL,
  `bildungsurlaub` varchar(255) DEFAULT NULL,
  `auPair` varchar(255) DEFAULT NULL,
  `fechMatConfirmacion` date DEFAULT NULL,
  `matCurso` varchar(255) DEFAULT NULL,
  `matAloja` varchar(255) DEFAULT NULL,
  `matFechInicio` date DEFAULT NULL,
  `obsPrescriptor` longtext,
  `estPrescripcion` int DEFAULT '1',
  `tokenPrescriptores` longtext COMMENT 'Token Preinscriptor',
  `numLlegada` varchar(225) DEFAULT NULL COMMENT 'Es el numero de llegada de l apersona, se traslada posteriormente a facturacion',
  `idDepartamentoEdu_prescriptores` int DEFAULT NULL COMMENT 'Viene de la tabla  tm_departamento_edu',
  `fecPrescripcion` date DEFAULT NULL,
  `tipoDocumento` varchar(225) DEFAULT NULL COMMENT 'Hae referencia al tipo, dni pasaporte...',
  `identificadorDocumento` varchar(225) DEFAULT NULL COMMENT 'Numero del identificador',
  `nombreMadrePre` varchar(225) DEFAULT NULL COMMENT 'Nombre y apellidos de la madre',
  `nombrePadrePre` varchar(225) DEFAULT NULL COMMENT 'Nombre y apellidos de la Padre',
  `numPadrePre` varchar(20) DEFAULT NULL COMMENT 'Telefono del padre',
  `numMadrePre` varchar(20) DEFAULT NULL COMMENT 'Telefono de la madre',
  `interesadoOnlinePre` int DEFAULT NULL COMMENT '0/1 Interesado en curso online',
  `nacionalidadPreinscriptor` varchar(255) DEFAULT NULL COMMENT 'Nacionalidad o idioma',
  `preferenciaHoraria` int DEFAULT '0' COMMENT '1= MAñanas 2=Tardes 0=Sin preferencais'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
